/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LeadershipRouteImport } from './routes/leadership'
import { Route as ChurchesRouteImport } from './routes/churches'
import { Route as UnitsRouteImport } from './routes/units'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as GiveRouteImport } from './routes/give'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as GalleryRouteImport } from './routes/gallery'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadershipRoute = LeadershipRouteImport.update({ id: '/leadership', path: '/leadership', getParentRoute: () => rootRouteImport } as any)
const ChurchesRoute = ChurchesRouteImport.update({ id: '/churches', path: '/churches', getParentRoute: () => rootRouteImport } as any)
const UnitsRoute = UnitsRouteImport.update({ id: '/units', path: '/units', getParentRoute: () => rootRouteImport } as any)
const EventsRoute = EventsRouteImport.update({ id: '/events', path: '/events', getParentRoute: () => rootRouteImport } as any)
const ResourcesRoute = ResourcesRouteImport.update({ id: '/resources', path: '/resources', getParentRoute: () => rootRouteImport } as any)
const GiveRoute = GiveRouteImport.update({ id: '/give', path: '/give', getParentRoute: () => rootRouteImport } as any)
const ConnectRoute = ConnectRouteImport.update({ id: '/connect', path: '/connect', getParentRoute: () => rootRouteImport } as any)
const PrivacyRoute = PrivacyRouteImport.update({ id: '/privacy', path: '/privacy', getParentRoute: () => rootRouteImport } as any)
const GalleryRoute = GalleryRouteImport.update({ id: '/gallery', path: '/gallery', getParentRoute: () => rootRouteImport } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/leadership': typeof LeadershipRoute
  '/churches': typeof ChurchesRoute
  '/units': typeof UnitsRoute
  '/services': typeof ServicesRoute
  '/events': typeof EventsRoute
  '/resources': typeof ResourcesRoute
  '/give': typeof GiveRoute
  '/connect': typeof ConnectRoute
  '/privacy': typeof PrivacyRoute
  '/gallery': typeof GalleryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/leadership': typeof LeadershipRoute
  '/churches': typeof ChurchesRoute
  '/units': typeof UnitsRoute
  '/services': typeof ServicesRoute
  '/events': typeof EventsRoute
  '/resources': typeof ResourcesRoute
  '/give': typeof GiveRoute
  '/connect': typeof ConnectRoute
  '/privacy': typeof PrivacyRoute
  '/gallery': typeof GalleryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/leadership': typeof LeadershipRoute
  '/churches': typeof ChurchesRoute
  '/units': typeof UnitsRoute
  '/services': typeof ServicesRoute
  '/events': typeof EventsRoute
  '/resources': typeof ResourcesRoute
  '/give': typeof GiveRoute
  '/connect': typeof ConnectRoute
  '/privacy': typeof PrivacyRoute
  '/gallery': typeof GalleryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/contact' | '/leadership' | '/churches' | '/units' | '/services' | '/events' | '/resources' | '/give' | '/connect' | '/privacy' | '/gallery'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/contact' | '/leadership' | '/churches' | '/units' | '/services' | '/events' | '/resources' | '/give' | '/connect' | '/privacy' | '/gallery'
  id: '__root__' | '/' | '/about' | '/contact' | '/leadership' | '/churches' | '/units' | '/services' | '/events' | '/resources' | '/give' | '/connect' | '/privacy' | '/gallery'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  LeadershipRoute: typeof LeadershipRoute
  ChurchesRoute: typeof ChurchesRoute
  UnitsRoute: typeof UnitsRoute
  ServicesRoute: typeof ServicesRoute
  EventsRoute: typeof EventsRoute
  ResourcesRoute: typeof ResourcesRoute
  GiveRoute: typeof GiveRoute
  ConnectRoute: typeof ConnectRoute
  PrivacyRoute: typeof PrivacyRoute
  GalleryRoute: typeof GalleryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership': { id: '/leadership'; path: '/leadership'; fullPath: '/leadership'; preLoaderRoute: typeof LeadershipRouteImport; parentRoute: typeof rootRouteImport }
    '/churches': { id: '/churches'; path: '/churches'; fullPath: '/churches'; preLoaderRoute: typeof ChurchesRouteImport; parentRoute: typeof rootRouteImport }
    '/units': { id: '/units'; path: '/units'; fullPath: '/units'; preLoaderRoute: typeof UnitsRouteImport; parentRoute: typeof rootRouteImport }
    '/services': { id: '/services'; path: '/services'; fullPath: '/services'; preLoaderRoute: typeof ServicesRouteImport; parentRoute: typeof rootRouteImport }
    '/events': { id: '/events'; path: '/events'; fullPath: '/events'; preLoaderRoute: typeof EventsRouteImport; parentRoute: typeof rootRouteImport }
    '/resources': { id: '/resources'; path: '/resources'; fullPath: '/resources'; preLoaderRoute: typeof ResourcesRouteImport; parentRoute: typeof rootRouteImport }
    '/give': { id: '/give'; path: '/give'; fullPath: '/give'; preLoaderRoute: typeof GiveRouteImport; parentRoute: typeof rootRouteImport }
    '/connect': { id: '/connect'; path: '/connect'; fullPath: '/connect'; preLoaderRoute: typeof ConnectRouteImport; parentRoute: typeof rootRouteImport }
    '/privacy': { id: '/privacy'; path: '/privacy'; fullPath: '/privacy'; preLoaderRoute: typeof PrivacyRouteImport; parentRoute: typeof rootRouteImport }
    '/gallery': { id: '/gallery'; path: '/gallery'; fullPath: '/gallery'; preLoaderRoute: typeof GalleryRouteImport; parentRoute: typeof rootRouteImport }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  LeadershipRoute,
  ChurchesRoute,
  UnitsRoute,
  EventsRoute,
  ResourcesRoute,
  GiveRoute,
  ConnectRoute,
  PrivacyRoute,
  GalleryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
